# zsh
## Setup
plugins=(
  git
  brew
)
export ZSH=$HOME/.dotfiles/zsh/src
source $ZSH/oh-my-zsh.sh
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export LESS="-R"
export PAGER='less -KFX'

# Don't require escaping globbing characters in zsh.
unsetopt nomatch

# HomeBrew
# Turn-off Analytic, sorry, hate being tracked
export HOMEBREW_NO_ANALYTICS=1
# Homebrew auto-update just once a week
export HOMEBREW_AUTO_UPDATE_SECS=604800

# Basic
# Big shared history
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=2000000

setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY

# Merge history before each prompt
autoload -Uz add-zsh-hook
history_merge() { fc -R; }   # fc -R == history -n
add-zsh-hook precmd history_merge

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='rmate -w'
else
  export EDITOR='subl -w'
fi

function o() {
  z $1 && open .
}

# $PATH
export PATH=/usr/local/bin:$PATH

# Homebrew in non-default location
export PATH="$HOME/homebrew/bin:$HOME/homebrew/sbin:$PATH"

# Local Binaries
export PATH="$PATH:$HOME/.local/bin"

# posh
export PATH="$PATH:$HOME/.dotfiles/posh/bin"

# pyenv
if command -v pyenv >/dev/null; then
  export PATH=$(pyenv root)/bin:$PATH
  eval "$(pyenv init -)"
fi

# Ruby & RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Oh My Posh
eval "$(oh-my-posh init zsh --config $HOME/.dotfiles/config/posh.json)"

# git
source ~/.dotfiles/git/github-pr.sh
## Alias

# Xcode
## Many thanks to @orta
openx() {
  if test -n "$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)"; then
    echo "Opening workspace"
    open *.xcworkspace
    return
  else
    if test -n "$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)"; then
      echo "Opening project"
      open *.xcodeproj
      return
    else
      echo "Nothing found"
    fi
  fi
}

# Local Only
if [ -f ~/.profile ]; then
  source ~/.profile
fi

# Private Only
if [ -f ~/.dotfiles-private/bash_profile ]; then
  source ~/.dotfiles-private/bash_profile
fi

# Aliases
source ~/.dotfiles/zsh/aliases

# added by setup_fb4a.sh
export ANDROID_SDK=/opt/android_sdk
export ANDROID_NDK_REPOSITORY=/opt/android_ndk
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/emulator:${ANDROID_SDK}/tools:${ANDROID_SDK}/tools/bin:${ANDROID_SDK}/platform-tools
